import "../styles/globals.css"
import { ChakraProvider } from '@chakra-ui/react'
import Head from 'next/head'
export default function App({ Component, pageProps }) {
  return (
    <>
      <ChakraProvider>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="viewport-fit=cover" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}

      </Head>
        <Component {...pageProps} />
      </ChakraProvider>

    </>
  )
}
