import Layout from "@/components/layout/Layout"
import "../styles/globals.css"
import { ChakraProvider } from '@chakra-ui/react'
import Head from 'next/head'
// Import the styles provided by the react-pdf-viewer packages
import '@react-pdf-viewer/core/lib/styles/index.css';
import '@react-pdf-viewer/default-layout/lib/styles/index.css';
export default function App({ Component, pageProps }) {
  return (
    <>
      <ChakraProvider>
        <Head>
          <title>Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          {/* <meta name="viewport" content="viewport-fit=cover" /> */}
          {/* i will pick one of them leter !!! */}
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {/* <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/> */}

        </Head>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ChakraProvider>

    </>
  )
}
