import Head from 'next/head'
import TypeWriter from '../components/TypeWriter'
import MouseTraker from '../components/MouseTraker'





export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <>
          <MouseTraker />
          <TypeWriter >
          </TypeWriter>
        </>

      </main>
    </>
  )
}
